### Consultar Todas las Casas de la DB
GET http://localhost:3000/api/casas/

### Consultar una casa por Id
GET http://localhost:3000/api/casas/66b17cac688e7382fb2f2260

### Consultar Casas por Ciudad
GET http://localhost:3000/api/casas/filtros/ciudad/Rosario

### Crear nueva Casa
POST http://localhost:3000/api/casas/
Content-Type: application/json

{
    "tipo": "Casa",
    "locacion": "Temporario",
    "ciudad": "Ramos Mejia",
    "provincia": "Buenos Aires",
    "foto": "/assets/foto4.jpg",
    "ambientes": "tres"
}

### Editar una Casa.
PUT  http://localhost:3000/api/casas/66b260f10a36029a6cb0e213
Content-Type: application/json

{
    "tipo": "Casa PH",
    "locacion": "Prolongado",
    "ciudad": "Ramos Mejia",
    "provincia": "Buenos Aires",
    "foto": "/assets/foto3.jpg",
    "ambientes": "cuatro"
}

### Eiminar una Casa.
DELETE http://localhost:3000/api/casas/66b2a2615a232a4804fe9a8b